# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Aslanides's weblog
email: 
description: > # this means to ignore newlines until "baseurl:"
  Self-indulgent rambling on topics in science, mathematics, music, architecture, sport, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aslanides.github.io" # the base hostname & protocol for your site
twitter_username: john_aslanides
github_username:  aslanides

# Build settings
#markdown: kramdown
markdown: redcarpet
permalink: pretty